eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 7077

# Spring Cloud Config (Add this if using a Config Server)
# spring:
#   config:
#     import: configserver:http://localhost:8888
# If not using a Config Server, disable the check
spring:
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: Project-service
          uri: lb://Project-service
          predicates:
            - Path=/project/**
        - id: Company-service
          uri: lb://Company-service
          predicates:
            - Path=/company/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

# Logging
logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    reactor.netty.http.client: DEBUG

# Enable all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always

