eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9095
spring:
  application:
    name: Employee-Service
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: tiger
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
